os: linux
dist: xenial
language: ruby
cache: bundler
before_install:
  - gem install bundler
env:
  - "TEST_GROUP=1"
  - "TEST_GROUP=2"
  - "TEST_GROUP=3"
  - "TEST_GROUP=4"
rvm:
  - 2.5
  - 2.6
  - 2.7
stages:
  - lint
  - test
jobs:
  fast_finish: true
  include:
    - stage: lint
      rvm: 2.7
      script: bundle exec rubocop
